// --- EXTRAS & ZUSÄTZE ---
const pizzaPath = "/products/pizza";
const softDrinkPath = "/products/kalte_getränke";

// Quelle: Alle Menükarten (Pizza, Pasta, Smoothies)
export const extras = {
  pizza: [
    { name: "Extra Käse", price: 2.5 },
    { name: "Salami", price: 2.5 },
    { name: "Schinken", price: 2.5 },
    { name: "Hähnchen", price: 3.0 },
    { name: "Champignons", price: 2.5 },
    { name: "Oliven", price: 2.5 },
    { name: "Paprika", price: 2.5 },
    { name: "Jalapeños", price: 2.5 },
    { name: "Ananas", price: 2.5 },
    { name: "Rucola", price: 3.0 },
    { name: "Thunfisch", price: 3.0 },
  ],
};

export const products = [
  // --- PIZZA ---
  {
    id: "pizza-1",
    name: "Pizza Margherita",
    slug: "margherita",
    description: "Tomatensauce, Mozzarella",
    category: "Pizza",
    imageUrl: `${pizzaPath}/margherita.webp`,
    imageAlt: "Pizza Margherita",
    prices: { S: 8.5, M: 10.5, L: 13.5 },
    isBestSeller: true,
  },
  {
    id: "pizza-2",
    name: "Pizza Salami",
    slug: "salami",
    description: "Tomatensauce, Salami",
    category: "Pizza",
    imageUrl: `${pizzaPath}/salami.webp`,
    imageAlt: "Pizza Salami",
    prices: { S: 9.5, M: 11.5, L: 14.5 },
    isBestSeller: true,
  },
  {
    id: "pizza-3",
    name: "Pizza Prosciutto",
    slug: "prosciutto",
    description: "Tomatensauce, Schinken",
    category: "Pizza",
    imageUrl: `${pizzaPath}/prosciutto.webp`,
    imageAlt: "Pizza Prosciutto",
    prices: { S: 9.5, M: 11.5, L: 14.5 },
    isBestSeller: false,
  },
  {
    id: "pizza-4",
    name: "Pizza Funghi",
    slug: "funghi",
    description: "Tomatensauce, Champignons",
    category: "Pizza",
    imageUrl: `${pizzaPath}/funghi.webp`,
    imageAlt: "Pizza Funghi",
    prices: { S: 9.0, M: 11.0, L: 14.0 },
    isBestSeller: false,
  },
  {
    id: "pizza-5",
    name: "Pizza Hawaii",
    slug: "hawaii",
    description: "Schinken, Ananas",
    category: "Pizza",
    imageUrl: `${pizzaPath}/hawaii.webp`,
    imageAlt: "Pizza Hawaii",
    prices: { S: 9.5, M: 11.5, L: 14.5 },
    isBestSeller: false,
  },
  {
    id: "pizza-6",
    name: "Pizza Tonno & Zwiebeln",
    slug: "tonno-zwiebeln",
    description: "Thunfisch, Zwiebeln",
    category: "Pizza",
    imageUrl: `${pizzaPath}/tonno-zwiebeln.webp`,
    imageAlt: "Pizza Tonno",
    prices: { S: 9.5, M: 11.5, L: 15.0 },
    isBestSeller: false,
  },
  {
    id: "pizza-9",
    name: "Pizza BBQ Chicken",
    slug: "bbq-chicken",
    description: "BBQ-Sauce, Hähnchen, Zwiebeln",
    category: "Pizza",
    imageUrl: `${pizzaPath}/bbq-chicken.webp`,
    imageAlt: "Pizza BBQ Chicken",
    prices: { S: 10.8, M: 12.8, L: 16.5 },
    isBestSeller: false,
  },
  {
    id: "pizza-10",
    name: "Pizza Vegetarisch",
    slug: "vegetarisch",
    description: "Gemüse, Käse",
    category: "Pizza",
    imageUrl: `${pizzaPath}/vegetarisch.webp`,
    imageAlt: "Pizza Vegetarisch",
    prices: { S: 10.8, M: 12.8, L: 16.5 },
    isBestSeller: false,
  },
  {
    id: "pizza-11",
    name: "Pizza Quattro Formaggi",
    slug: "quattro-formaggi",
    description: "Vier Käsesorten",
    category: "Pizza",
    imageUrl: `${pizzaPath}/quattro-formaggi.webp`,
    imageAlt: "Pizza Quattro Formaggi",
    prices: { S: 11.5, M: 13.5, L: 17.0 },
    isBestSeller: false,
  },
  {
    id: "pizza-12",
    name: "Pizza Sucuk",
    slug: "sucuk",
    description: "Sucuk, Zwiebeln",
    category: "Pizza",
    imageUrl: `${pizzaPath}/sucuk.webp`,
    imageAlt: "Pizza Sucuk",
    prices: { S: 10.8, M: 13.8, L: 16.5 },
    isBestSeller: false,
  },
  {
    id: "pizza-13",
    name: "Pizza Polo",
    slug: "polo",
    description: "Hähnchen, Champignons",
    category: "Pizza",
    imageUrl: `${pizzaPath}/polo.webp`,
    imageAlt: "Pizza Polo",
    prices: { S: 10.8, M: 12.8, L: 16.5 },
    isBestSeller: false,
  },
  {
    id: "pizza-14",
    name: "Pizza Tonno Supreme",
    slug: "tonno-supreme",
    description: "Thunfisch, Oliven, Zwiebeln",
    category: "Pizza",
    imageUrl: `${pizzaPath}/tonno-supreme.webp`,
    imageAlt: "Pizza Tonno Supreme",
    prices: { S: 11.0, M: 13.8, L: 17.0 },
    isBestSeller: false,
  },

  // --- KALTE GETRÄNKE ---
  {
    id: "soft-1",
    name: "Coca-Cola",
    slug: "coca-cola",
    description: "Klassisch",
    category: "Kalte Getränke",
    imageUrl: `${softDrinkPath}/cola.webp`,
    imageAlt: "Coca-Cola",
    prices: { Dose: 2.5 },
    isBestSeller: true,
  },
  {
    id: "soft-2",
    name: "Coca-Cola Light",
    slug: "coca-cola-light",
    description: "Zuckerfrei",
    category: "Kalte Getränke",
    imageUrl: `${softDrinkPath}/cola_light.webp`,
    imageAlt: "Coca-Cola Light",
    prices: { Dose: 2.5 },
    isBestSeller: false,
  },
  {
    id: "soft-3",
    name: "Coca-Cola Zero",
    slug: "coca-cola-zero",
    description: "Zuckerfrei, Zero Kalorien",
    category: "Kalte Getränke",
    imageUrl: `${softDrinkPath}/cola_zero.webp`,
    imageAlt: "Coca-Cola Zero",
    prices: { Dose: 2.5 },
    isBestSeller: false,
  },
  {
    id: "soft-4",
    name: "Fanta Orange",
    slug: "fanta",
    description: "Orangen-Geschmack",
    category: "Kalte Getränke",
    imageUrl: `${softDrinkPath}/fanta_orange.webp`,
    imageAlt: "Fanta",
    prices: { Dose: 2.5 },
    isBestSeller: false,
  },
  {
    id: "soft-5",
    name: "Sprite",
    slug: "sprite",
    description: "Zitronen-Limetten-Geschmack",
    category: "Kalte Getränke",
    imageUrl: `${softDrinkPath}/sprite.webp`,
    imageAlt: "Sprite",
    prices: { Dose: 2.5 },
    isBestSeller: false,
  },
  {
    id: "soft-6",
    name: "Red Bull",
    slug: "red-bull",
    description: "Zitronen-Limetten-Geschmack",
    category: "Kalte Getränke",
    imageUrl: `${softDrinkPath}/rb_zitronen.webp`,
    imageAlt: "Red Bull",
    prices: { Dose: 3.0 },
    isBestSeller: false,
  },
  {
    id: "soft-7",
    name: "Red Bull Energy",
    slug: "red-bull-energy",
    description: "Energy Drink",
    category: "Kalte Getränke",
    imageUrl: `${softDrinkPath}/rb.webp`,
    imageAlt: "Red Bull Energy",
    prices: { Dose: 3.0 },
    isBestSeller: false,
  },
  {
    id: "soft-8",
    name: "Red Bull Sugarfree",
    slug: "red-bull-sugarfree",
    description: "Zuckerfreie Variante",
    category: "Kalte Getränke",
    imageUrl: `${softDrinkPath}/rb_sugerfree.webp`,
    imageAlt: "Red Bull Sugarfree",
    prices: { Dose: 3.0 },
    isBestSeller: false,
  },
  {
    id: "soft-9",
    name: "Mineralwasser Sprudel",
    slug: "wasser-sprudel",
    description: "Mit Kohlensäure",
    category: "Kalte Getränke",
    imageUrl: `${softDrinkPath}/wasser_sprudel.webp`,
    imageAlt: "Mineralwasser Sprudel",
    prices: { Flasche: 2.0 },
    isBestSeller: false,
  },
  {
    id: "soft-10",
    name: "Mineralwasser Still",
    slug: "wasser-still",
    description: "Ohne Kohlensäure",
    category: "Kalte Getränke",
    imageUrl: `${softDrinkPath}/wasser_still.webp`,
    imageAlt: "Mineralwasser Still",
    prices: { Flasche: 2.0 },
    isBestSeller: false,
  },
];
